# Generated by Django 5.1.5 on 2025-07-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_post_image_post_video_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
